### ISSUE TITLE
Spell not found on action bars: Unstable Affliction 316099

### ISSUE THREAD

**Issue by ghost** [Vae2009/ConRO_Warlock#1]
No error being thrown on it, but getting spammed with the message. FWIW I have another rotation addon saying the same thing. But I do have UA on my bars and even tried replacing it by dragging it off the talent tree UI to see if that would help (it didn't).

**Comment by Vae2009** [comment]
If you could link me your build from the import feature on the talent tree. I would appreciate it.

**Comment by ghost** [comment]
Oh ffs... I included it when I posted on Discord and then forgot when I deleted that and brought the bug here. Sorry.

BkQAbtPS25JQs0VfQSDmhm+p3ggIABQLik0SCJpAAAAAQCAAAAAAIoFJkkkkEFBAA

**Comment by Vae2009** [comment]
This should now be resolved, issue was with warmode Rampant Affliction
