### ISSUE TITLE
In-combat error

### ISSUE THREAD

**Issue by ghost** [Vae2009/ConRO_Warlock#2]
I was doing the quest The Rumpus and may just have confused ConRO till it broke. Had it set to burst/single but I was getting dogpiled by waves of NPCs that died too quickly for Seed of Corruption to go off. but too slow if I didn't try dotting them up.

24x ConRO_Warlock/warlock.lua:452: attempt to compare number with nil
[string "@ConRO_Warlock/warlock.lua"]:452: in function `NextDef'
[string "@ConRO/core.lua"]:2432: in function `?'
[string "@ConRO/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...faceConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
_ = <table> {
 AbilityPurge = <function> defined @ConRO/buttons.lua:2790
 IsPvP = <function> defined @ConRO/helper.lua:43
 DestroyPurgableOverlays = <function> defined @ConRO/buttons.lua:1712
 modules = <table> {
 }
 CancelTimer = <function> defined @ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 DefFetchBlizzard = <function> defined @ConRO/buttons.lua:2266
 ItemEquipped = <function> defined @ConRO/helper.lua:140
 PurgeWindowFrame = <function> defined @ConRO/buttons.lua:1075
 InterruptGlow = <function> defined @ConRO/buttons.lua:1875
 ScheduleTimer = <function> defined @ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @ConRO/helper.lua:62
 CreateDefenseOverlay = <function> defined @ConRO/buttons.lua:1282
 Heroism = <function> defined @ConRO/helper.lua:304
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 InvokeNextDef = <function> defined @ConRO/core.lua:2427
 ClearAbilityRaidBuffsIndependent = <function> defined @ConRO/buttons.lua:2719
 CreateRaidBuffsOverlay = <function> defined @ConRO/buttons.lua:1546
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @ConRO/helper.lua:235
 DisplayNext2WindowFrame = <function> defined @ConRO/buttons.lua:900
 NewModule = <function> defined @CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 GlowNextDef = <function> defined @ConRO/buttons.lua:2920
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @ConRO/buttons.lua:1216
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @ConRO/helper.lua:726
 Dump = <function> defined @ConRO/buttons.lua:2627
 Colors = <table> {
 }
 RaidBuff = <function> defined @ConRO/helper.lua:392
 ClearAbilityInterruptIndependent = <function> defined @ConRO/buttons.lua:2695
 ToggleDamage = <function> defined @ConRO/buttons.lua:718
 Disable = <function> defined @CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @ConRO/core.lua:2287
 Print = <function> defined @ConRO/core.lua:2036
 BurstMode = <function> defined @ConRO/helper.lua:74
 LEARNED_SPELL_IN_TAB = <function> defined @ConRO/core.lua:2362
 HideTauntGlow = <function> defined @ConRO/buttons.lua:1983
 HideDefenseGlow = <function> defined @ConRO/buttons.lua:1959
 CreateBurstButton = <function> defined @ConRO/buttons.lua:483
 Totem = <function> defined @ConRO/helper.lua:984
 SlashUnlock = <function> defined @ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <function> defined @ConRO/helper.lua:810
 EnableModule = <function> defined @CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 IterateEmbeds = <function> defined @CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 RaidBuffsFramePool = <table> {
 }
 DefenseFramePool = <table> {
 }
 BlockAoE = <function> defined @ConRO/buttons.lua:759
 Interrupt = <function> defined @ConRO/helper.lua:922
 ButtonFetch = <function> defined @ConRO/core.lua:2362
 ACTIONBAR_HIDEGRID = <function> defined @ConRO/core.lua:2209
 defaultModuleState = true
 Warnings = <f

**Comment by Vae2009** [comment]
I believe this one has been resolved.
