### ISSUE TITLE
LUA Error hell

### ISSUE THREAD

**Issue by squish88** [Vae2009/ConRO_Warlock#3]
While fighting Firava the Rekindler...

Message: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
Time: Fri Dec  2 17:11:56 2022
Count: 3
Stack: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
[string "@Interface/AddOns/ConRO_Warlock/warlock.lua"]:497: in function `NextDef'
[string "@Interface/AddOns/ConRO/core.lua"]:2452: in function `?'
[string "@Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...face/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: _ = <table> {
 AbilityPurge = <function> defined @Interface/AddOns/ConRO/buttons.lua:2790
 IsPvP = <function> defined @Interface/AddOns/ConRO/helper.lua:47
 DestroyPurgableOverlays = <function> defined @Interface/AddOns/ConRO/buttons.lua:1712
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 AbilityInterrupt = <function> defined @Interface/AddOns/ConRO/buttons.lua:2750
 ItemEquipped = <function> defined @Interface/AddOns/ConRO/helper.lua:144
 PurgeWindowFrame = <function> defined @Interface/AddOns/ConRO/buttons.lua:1075
 InterruptGlow = <function> defined @Interface/AddOns/ConRO/buttons.lua:1875
 ScheduleTimer = <function> defined @Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @Interface/AddOns/ConRO/helper.lua:66
 CreateDefenseOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1282
 Heroism = <function> defined @Interface/AddOns/ConRO/helper.lua:309
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 PLAYER_LOSES_VEHICLE_DATA = <function> defined @Interface/AddOns/ConRO/core.lua:2255
 ClearAbilityRaidBuffsIndependent = <function> defined @Interface/AddOns/ConRO/buttons.lua:2719
 CreateRaidBuffsOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1546
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @Interface/AddOns/ConRO/helper.lua:240
 DisplayNext2WindowFrame = <function> defined @Interface/AddOns/ConRO/buttons.lua:900
 NewModule = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 GlowNextDef = <function> defined @Interface/AddOns/ConRO/buttons.lua:2920
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1216
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @Interface/AddOns/ConRO/helper.lua:731
 Dump = <function> defined @Interface/AddOns/ConRO/buttons.lua:2627
 name = "ConRO"
 RaidBuff = <function> defined @Interface/AddOns/ConRO/helper.lua:397
 ClearAbilityInterruptIndependent = <function> defined @Interface/AddOns/ConRO/buttons.lua:2695
 ToggleDamage = <function> defined @Interface/AddOns/ConRO/buttons.lua:718
 Disable = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @Interface/AddOns/ConRO/core.lua:2307
 Print = <function> defined @Interface/AddOns/ConRO/core.lua:2036
 BurstMode = <function> defined @Interface/AddOns/ConRO/helper.lua:78
 LEARNED_SPELL_IN_TAB = <function> defined @Interface/AddOns/ConRO/core.lua:2382
 HideTauntGlow = <function> defined @Interface/AddOns/ConRO/buttons.lua:1983
 DefFetchDiabolic = <function> defined @Interface/AddOns/ConRO/buttons.lua:2537
 CreateBurstButton = <function> defined @Interface/AddOns/ConRO/buttons.lua:483
 Totem = <function> defined @Interface/AddOns/ConRO/helper.lua:989
 SlashUnlock = <function> defined @Interface/AddOns/ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <function> defined @Interface/AddOns/C

Message: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
Time: Fri Dec  2 17:11:36 2022
Count: 1
Stack: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
[string "@Interface/AddOns/ConRO_Warlock/warlock.lua"]:497: in function `NextDef'
[string "@Interface/AddOns/ConRO/core.lua"]:2452: in function `InvokeNextDef'
[string "@Interface/AddOns/ConRO/core.lua"]:2345: in function `?'
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals: <none>

Message: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
Time: Fri Dec  2 17:11:40 2022
Count: 1
Stack: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
[string "@Interface/AddOns/ConRO_Warlock/warlock.lua"]:497: in function `NextDef'
[string "@Interface/AddOns/ConRO/core.lua"]:2452: in function `InvokeNextDef'
[string "@Interface/AddOns/ConRO/core.lua"]:2345: in function `?'
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `TargetNearestEnemy'
[string "TARGETNEARESTENEMY"]:2: in function <[string "TARGETNEARESTENEMY"]:1>

Locals: <none>

Message: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
Time: Fri Dec  2 17:11:56 2022
Count: 2
Stack: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
[string "@Interface/AddOns/ConRO_Warlock/warlock.lua"]:497: in function `NextDef'
[string "@Interface/AddOns/ConRO/core.lua"]:2452: in function `InvokeNextDef'
[string "@Interface/AddOns/ConRO/buttons.lua"]:2234: in function `?'
[string "@Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...face/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: _ = <table> {
 AbilityPurge = <function> defined @Interface/AddOns/ConRO/buttons.lua:2790
 IsPvP = <function> defined @Interface/AddOns/ConRO/helper.lua:47
 DestroyPurgableOverlays = <function> defined @Interface/AddOns/ConRO/buttons.lua:1712
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 AbilityInterrupt = <function> defined @Interface/AddOns/ConRO/buttons.lua:2750
 ItemEquipped = <function> defined @Interface/AddOns/ConRO/helper.lua:144
 PurgeWindowFrame = <function> defined @Interface/AddOns/ConRO/buttons.lua:1075
 InterruptGlow = <function> defined @Interface/AddOns/ConRO/buttons.lua:1875
 ScheduleTimer = <function> defined @Interface/AddOns/ConRO/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @Interface/AddOns/ConRO/helper.lua:66
 CreateDefenseOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1282
 Heroism = <function> defined @Interface/AddOns/ConRO/helper.lua:309
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 PLAYER_LOSES_VEHICLE_DATA = <function> defined @Interface/AddOns/ConRO/core.lua:2255
 ClearAbilityRaidBuffsIndependent = <function> defined @Interface/AddOns/ConRO/buttons.lua:2719
 CreateRaidBuffsOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1546
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @Interface/AddOns/ConRO/helper.lua:240
 DisplayNext2WindowFrame = <function> defined @Interface/AddOns/ConRO/buttons.lua:900
 NewModule = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 GlowNextDef = <function> defined @Interface/AddOns/ConRO/buttons.lua:2920
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @Interface/AddOns/ConRO/buttons.lua:1216
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @Interface/AddOns/ConRO/helper.lua:731
 Dump = <function> defined @Interface/AddOns/ConRO/buttons.lua:2627
 name = "ConRO"
 RaidBuff = <function> defined @Interface/AddOns/ConRO/helper.lua:397
 ClearAbilityInterruptIndependent = <function> defined @Interface/AddOns/ConRO/buttons.lua:2695
 ToggleDamage = <function> defined @Interface/AddOns/ConRO/buttons.lua:718
 Disable = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @Interface/AddOns/ConRO/core.lua:2307
 Print = <function> defined @Interface/AddOns/ConRO/core.lua:2036
 BurstMode = <function> defined @Interface/AddOns/ConRO/helper.lua:78
 LEARNED_SPELL_IN_TAB = <function> defined @Interface/AddOns/ConRO/core.lua:2382
 HideTauntGlow = <function> defined @Interface/AddOns/ConRO/buttons.lua:1983
 DefFetchDiabolic = <function> defined @Interface/AddOns/ConRO/buttons.lua:2537
 CreateBurstButton = <function> defined @Interface/AddOns/ConRO/buttons.lua:483
 Totem = <function> defined @Interface/AddOns/ConRO/helper.lua:989
 SlashUnlock = <function> defined @Interface/AddOns/ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lu

Message: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
Time: Fri Dec  2 17:11:44 2022
Count: 4
Stack: Interface/AddOns/ConRO_Warlock/warlock.lua:497: attempt to compare number with nil
[string "@Interface/AddOns/ConRO_Warlock/warlock.lua"]:497: in function `NextDef'
[string "@Interface/AddOns/ConRO/core.lua"]:2452: in function `InvokeNextDef'
[string "@Interface/AddOns/ConRO/core.lua"]:2345: in function `?'
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...igs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BigWigs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Vae2009** [comment]
Found the bad code, will update
