### ISSUE TITLE
Chaos Bolt never in rotation for Destro

### ISSUE THREAD

**Issue by elsbithe** [Vae2009/ConRO_Warlock#4]
Here is my talent share:

BsQAbtPS25JQs0VfQSDmhm+p3QCyBSSSSCICItEJhCOQ4AKRCpkDk0KFRAAAAAAAAAAAAECtkE

**Comment by Vae2009** [comment]
Is this still happening?

**Comment by elsbithe** [comment]
I will check when I get home from work. Last night it was still happening
when I did the field of ferocity.

**Comment by elsbithe** [comment]
Yes as of an hour ago I went and did the hunt and still no chaos bolt. I followed the rotation suggestions exactly just in case I was causing it by veering off path. Sent from my iPhoneOn Dec 6, 2022, at 12:09 PM, Vae ***@***.***> wrote:﻿
Is this still happening?

**Comment by Vae2009** [comment]
Sorry for the delay in resolving this issue. I believe Ritual of Ruin is causing a buff that may change Chaos Bolts SpellID. I am trying to figure this out and will have a fix.

**Comment by Vae2009** [comment]
I have not found a way to duplicate this issue, I am closing the report. Feel free to reopen if it still isn't fixed.

**Comment by elsbithe** [comment]
It’s ok, I removed that talent and it fixed it. If i choose to take it again and the issue persists I will let you know. Sent from my iPhoneOn Dec 25, 2022, at 3:45 AM, Vae ***@***.***> wrote:﻿
I have not found a way to duplicate this issue, I am closing the report. Feel free to reopen if it still isn't fixed.
