### ISSUE TITLE
Guillotine not talented, but ConRo keeps suggesting it

### ISSUE THREAD

**Issue by jury** [Vae2009/ConRO_Warlock#7]
Hi there -- I'm running a Demonology spec and I notice that when I spec "Immutable Hatred" instead of "Guillotine" (they occupy the same talent node), ConRo still tries to get me to cast Guillotine instead.

Immutable Hatred is 405670 and is a passive. I'm not sure how to look up the talentID though.

Thank you very much for helping fix this!

**Comment by FouadKhouri** [comment]
Have the same issue - had a look in the lua files and there's no mention of Immutable Hatred.

**Comment by Vae2009** [comment]
Should be fixed
